import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np
from torch.utils.data import DataLoader

from .dataset import SpeedSkatingDataset
from .model import SkatingDegradationLSTM

def train_model():
    # 1. Load your real preprocessed CSV data from the data folder
    csv_path = "data/extracted_multivariate_angles.csv"
    
    try:
        df = pd.read_csv(csv_path)
        
        # Match these to the exact column names generated by your preprocessor
        feature_cols = ['left_knee_filtered', 'right_knee_filtered', 'right_hip_x', 'right_hip_y']
        
        # If your CSV does not have a degradation label yet, we create a dummy target column for unsupervised/supervised training structure
        if 'degradation_label' not in df.columns:
            # For demonstration, assign 0 (normal) to first half and 1 (fatigued) to second half, or all zeros
            df['degradation_label'] = np.linspace(0, 1, len(df))
            
        label_col = 'degradation_label'
        
        data_array = df[feature_cols].values
        labels_array = df[label_col].values
        
        # Normalize features for stable training
        data_array = (data_array - np.mean(data_array, axis=0)) / (np.std(data_array, axis=0) + 1e-8)
        
    except FileNotFoundError:
        print(f"Error: Could not find {csv_path}. Make sure you run preprocess_video.py first.")
        return
    
    # 2. Initialize Dataset and DataLoader using your existing dataset.py
    window_size = 30  # Adjusted to fit your frame count nicely
    dataset = SpeedSkatingDataset(data_array, labels_array, window_size=window_size)
    dataloader = DataLoader(dataset, batch_size=32, shuffle=True)
    
    # 3. Initialize Model, Loss Function, and Optimizer
    input_dim = len(feature_cols)
    model = SkatingDegradationLSTM(input_dim=input_dim, hidden_dim=64, num_layers=2, output_dim=1)
    
    criterion = nn.BCELoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)
    
    # 4. Training Loop
    num_epochs = 5
    model.train()
    
    print("Starting training loop on Sven Kramer skating data...")
    for epoch in range(num_epochs):
        epoch_loss = 0.0
        for batch_x, batch_y in dataloader:
            optimizer.zero_grad()
            predictions = model(batch_x).squeeze()
            loss = criterion(predictions, batch_y.float())
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
            
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {epoch_loss / len(dataloader):.4f}")
        
    print("Training complete! Model successfully trained on real kinematic sequences.")
    torch.save(model.state_dict(), "skating_degradation_model.pth")
    print("Model weights saved to skating_degradation_model.pth")

if __name__ == "__main__":
    train_model()